# Generated by Django 6.0.6 on 2026-09-01 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatroom_chatmessage_ordermedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(max_length=500)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ai_suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('market', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('expired', 'Expired')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField()),
                ('fisherman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.fishspecies')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
