# Generated by Django 6.0.6 on 2026-09-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fishproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
