import { useState, useEffect } from 'react'
import axios from 'axios'
import { FileSpreadsheet, Printer, Download, Calendar, TrendingUp, DollarSign, CheckCircle, Clock, XCircle, FileText, Activity } from 'lucide-react'

const API = 'https://samaki-smart-ai.onrender.com/api/auth'

export default function AdminReportsPage({ token }) {
  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(false)
  const [statusFilter, setStatusFilter] = useState('all')
  const [periodFilter, setPeriodFilter] = useState('7days')
  const [reportType, setReportType] = useState('orders')

  const fetchReport = async () => {
    setLoading(true)
    try {
      const res = await axios.get(`${API}/admin/reports/`, {
        headers: { Authorization: `Bearer ${token}` },
        params: { type: reportType, status: statusFilter, period: periodFilter }
      })
      setReport(res.data)
    } catch (e) {
      alert('Failed to generate report')
    }
    setLoading(false)
  }

  useEffect(() => {
    fetchReport()
  }, [statusFilter, periodFilter, reportType])

  // Calculate transaction statistics
  const calculateStats = (orders) => {
    if (!orders || orders.length === 0) return null
    const totalValue = orders.reduce((sum, o) => sum + (o.total_value || 0), 0)
    const totalQty = orders.reduce((sum, o) => sum + (parseFloat(o.quantity_kg) || 0), 0)
    const avgPrice = totalQty > 0 ? totalValue / totalQty : 0
    const fulfilledValue = orders.filter(o => o.status === 'fulfilled').reduce((sum, o) => sum + (o.total_value || 0), 0)
    
    return {
      totalValue,
      totalQty,
      avgPrice,
      fulfilledValue,
      pendingValue: orders.filter(o => o.status === 'pending').reduce((sum, o) => sum + (o.total_value || 0), 0),
      acceptedValue: orders.filter(o => o.status === 'accepted').reduce((sum, o) => sum + (o.total_value || 0), 0),
      cancelledValue: orders.filter(o => o.status === 'cancelled').reduce((sum, o) => sum + (o.total_value || 0), 0),
    }
  }

  const stats = report ? calculateStats(report.orders) : null

  const exportCSV = () => {
    if (!report) return
    const rows = [
      ['SAMAKI SMART AI - OFFICIAL REPORT'],
      ['Generated:', report.generated_at],
      ['Generated By:', report.generated_by],
      ['Period:', report.period],
      ['Status Filter:', report.status_filter],
      [],
      ['SUMMARY'],
      ['Total Orders', report.summary.total_orders],
      ['Pending', report.summary.pending],
      ['Accepted', report.summary.accepted],
      ['Fulfilled', report.summary.fulfilled],
      ['Cancelled', report.summary.cancelled],
      ['Total Value (TZS)', stats ? stats.totalValue : 0],
      [],
      ['ORDER DETAILS'],
      ['Order #', 'Date', 'Time', 'Buyer', 'Buyer Phone', 'Seller', 'Seller Phone', 'Species', 'Qty (kg)', 'Price/kg', 'Total (TZS)', 'Status'],
      ...report.orders.map(o => [o.id, o.date, o.time, o.buyer_name, o.buyer_phone, o.seller_name, o.seller_phone, o.species, o.quantity_kg, o.price_tzs, o.total_value, o.status])
    ]
    const csv = rows.map(r => r.join(',')).join('\n')
    const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `samaki-report-${report.report_type}-${Date.now()}.csv`
    a.click()
    URL.revokeObjectURL(url)
  }

  const printReport = () => {
    window.print()
  }

  const getStatusBadge = (status) => {
    const configs = {
      pending: { bg: 'bg-amber-100', text: 'text-amber-700', border: 'border-amber-200' },
      accepted: { bg: 'bg-blue-100', text: 'text-blue-700', border: 'border-blue-200' },
      fulfilled: { bg: 'bg-emerald-100', text: 'text-emerald-700', border: 'border-emerald-200' },
      cancelled: { bg: 'bg-red-100', text: 'text-red-700', border: 'border-red-200' },
    }
    const config = configs[status] || configs.pending
    return (
      <span className={`inline-block px-2.5 py-1 rounded-full text-xs font-bold border ${config.bg} ${config.text} ${config.border}`}>
        {status.toUpperCase()}
      </span>
    )
  }

  return (
    <>
      {/* Print styles */}
      <style>{`
        @media print {
          body * { visibility: hidden; }
          #report-section, #report-section * { visibility: visible; }
          #report-section {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
            margin: 0;
            padding: 20px;
            box-shadow: none;
          }
          .no-print { display: none !important; }
          #report-section {
            max-width: 100% !important;
          }
          @page {
            size: A4 landscape;
            margin: 15mm;
          }
        }
      `}</style>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 py-6">
        {/* Header - no-print */}
        <div className="no-print mb-6">
          <h1 className="text-2xl font-bold text-white">📊 Official Reports</h1>
          <p className="text-gray-400 text-sm mt-1">Generate, export, and print official system reports</p>
        </div>

        {/* Filters - no-print */}
        <div className="no-print bg-[#111827] rounded-2xl border border-white/[0.05] p-5 mb-6">
          <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
            <div>
              <label className="text-xs font-semibold text-gray-500 uppercase mb-2 block">Report Type</label>
              <select value={reportType} onChange={e => setReportType(e.target.value)}
                className="w-full bg-[#0d1321] border border-white/[0.08] rounded-xl px-4 py-2.5 text-sm text-white">
                <option value="orders">📋 Orders Report</option>
                <option value="transactions">💰 Transaction Report</option>
                <option value="logs">🔍 System Logs</option>
              </select>
            </div>
            <div>
              <label className="text-xs font-semibold text-gray-500 uppercase mb-2 block">Status Filter</label>
              <select value={statusFilter} onChange={e => setStatusFilter(e.target.value)}
                className="w-full bg-[#0d1321] border border-white/[0.08] rounded-xl px-4 py-2.5 text-sm text-white">
                <option value="all">All Statuses</option>
                <option value="pending">⏳ Pending</option>
                <option value="accepted">✅ Accepted</option>
                <option value="fulfilled">🚚 Fulfilled</option>
                <option value="cancelled">❌ Cancelled</option>
              </select>
            </div>
            <div>
              <label className="text-xs font-semibold text-gray-500 uppercase mb-2 block">Time Period</label>
              <select value={periodFilter} onChange={e => setPeriodFilter(e.target.value)}
                className="w-full bg-[#0d1321] border border-white/[0.08] rounded-xl px-4 py-2.5 text-sm text-white">
                <option value="2hours">Last 2 Hours</option>
                <option value="today">Last 24 Hours</option>
                <option value="2days">Last 2 Days</option>
                <option value="7days">Last 7 Days</option>
                <option value="30days">Last 30 Days</option>
                <option value="monthly">This Month</option>
                <option value="yearly">This Year</option>
                <option value="all">All Time</option>
              </select>
            </div>
            <div className="flex items-end gap-2">
              <button onClick={exportCSV}
                className="flex-1 px-4 py-2.5 bg-emerald-600 hover:bg-emerald-700 rounded-xl text-white text-sm font-semibold transition-all flex items-center justify-center gap-2">
                <FileSpreadsheet size={16} /> Excel
              </button>
              <button onClick={printReport}
                className="flex-1 px-4 py-2.5 bg-blue-600 hover:bg-blue-700 rounded-xl text-white text-sm font-semibold transition-all flex items-center justify-center gap-2">
                <Printer size={16} /> Print
              </button>
            </div>
            <div className="flex items-end">
              <button onClick={fetchReport}
                className="w-full px-4 py-2.5 bg-cyan-600 hover:bg-cyan-700 rounded-xl text-white text-sm font-semibold transition-all flex items-center justify-center gap-2">
                <Download size={16} /> Generate
              </button>
            </div>
          </div>
        </div>

        {/* Report Preview */}
        {loading ? (
          <div className="flex justify-center py-20 no-print">
            <div className="animate-spin w-8 h-8 border-2 border-cyan-400 border-t-transparent rounded-full" />
          </div>
        ) : report ? (
          <div id="report-section" className="bg-white rounded-2xl shadow-xl overflow-hidden">
            {/* Report Header */}
            <div className="bg-gradient-to-r from-blue-800 to-cyan-700 px-8 py-6 text-white">
              <div className="flex items-center justify-between">
                <div>
                  <h2 className="text-2xl font-bold tracking-wide">SAMAKI SMART AI</h2>
                  <p className="text-sm opacity-90 mt-1">Official {report.report_type?.toUpperCase()} Report</p>
                </div>
                <div className="text-right">
                  <div className="w-16 h-16 bg-white/10 rounded-2xl flex items-center justify-center mx-auto mb-2">
                    <FileText size={32} />
                  </div>
                </div>
              </div>
            </div>

            {/* Report Meta */}
            <div className="px-8 py-4 bg-gray-50 border-b border-gray-200 grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
              <div>
                <p className="text-xs text-gray-500 font-semibold">GENERATED</p>
                <p className="font-medium text-gray-800">{report.generated_at}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 font-semibold">GENERATED BY</p>
                <p className="font-medium text-gray-800">{report.generated_by}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 font-semibold">PERIOD</p>
                <p className="font-medium text-gray-800">{report.period}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500 font-semibold">STATUS</p>
                <p className="font-medium text-gray-800">{report.status_filter}</p>
              </div>
            </div>

            {/* Summary Section */}
            <div className="px-8 py-5 border-b border-gray-200">
              <h3 className="font-bold text-gray-800 text-lg mb-3">EXECUTIVE SUMMARY</h3>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                <div className="bg-blue-50 border border-blue-100 rounded-xl p-3 text-center">
                  <p className="text-2xl font-black text-blue-700">{report.summary.total_orders}</p>
                  <p className="text-xs text-gray-600 font-semibold">TOTAL ORDERS</p>
                </div>
                <div className="bg-amber-50 border border-amber-100 rounded-xl p-3 text-center">
                  <p className="text-2xl font-black text-amber-700">{report.summary.pending}</p>
                  <p className="text-xs text-gray-600 font-semibold">PENDING</p>
                </div>
                <div className="bg-emerald-50 border border-emerald-100 rounded-xl p-3 text-center">
                  <p className="text-2xl font-black text-emerald-700">{report.summary.fulfilled}</p>
                  <p className="text-xs text-gray-600 font-semibold">FULFILLED</p>
                </div>
                <div className="bg-cyan-50 border border-cyan-100 rounded-xl p-3 text-center">
                  <p className="text-lg font-black text-cyan-700">TZS {stats ? stats.totalValue.toLocaleString() : '0'}</p>
                  <p className="text-xs text-gray-600 font-semibold">TOTAL VALUE</p>
                </div>
              </div>
            </div>

            {/* Transaction Details or Logs */}
            {reportType === 'logs' ? (
              <div className="px-8 py-5">
                <h3 className="font-bold text-gray-800 text-lg mb-3">SYSTEM AUDIT LOGS</h3>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead className="bg-gray-100">
                      <tr>
                        <th className="py-3 px-4 text-left font-semibold text-gray-600">#</th>
                        <th className="py-3 px-4 text-left font-semibold text-gray-600">Timestamp</th>
                        <th className="py-3 px-4 text-left font-semibold text-gray-600">User</th>
                        <th className="py-3 px-4 text-left font-semibold text-gray-600">Action</th>
                        <th className="py-3 px-4 text-left font-semibold text-gray-600">Table</th>
                        <th className="py-3 px-4 text-left font-semibold text-gray-600">Record ID</th>
                      </tr>
                    </thead>
                    <tbody>
                      {report.logs.map(log => (
                        <tr key={log.id} className="border-b border-gray-100 hover:bg-gray-50">
                          <td className="py-2.5 px-4">{log.id}</td>
                          <td className="py-2.5 px-4">{log.timestamp}</td>
                          <td className="py-2.5 px-4 font-medium">{log.user}</td>
                          <td className="py-2.5 px-4">
                            <span className="px-2 py-1 rounded-full text-xs font-bold bg-blue-50 text-blue-700 border border-blue-100">
                              {log.action}
                            </span>
                          </td>
                          <td className="py-2.5 px-4">{log.table}</td>
                          <td className="py-2.5 px-4 text-gray-500">#{log.record_id}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                  {report.logs.length === 0 && (
                    <p className="text-center text-gray-500 py-8">No logs found for this filter</p>
                  )}
                </div>
              </div>
            ) : (
              <div className="px-8 py-5">
                <h3 className="font-bold text-gray-800 text-lg mb-3">TRANSACTION DETAILS</h3>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead className="bg-gray-100">
                      <tr>
                        <th className="py-3 px-3 text-left font-semibold text-gray-600">Order #</th>
                        <th className="py-3 px-3 text-left font-semibold text-gray-600">Date & Time</th>
                        <th className="py-3 px-3 text-left font-semibold text-gray-600">Buyer</th>
                        <th className="py-3 px-3 text-left font-semibold text-gray-600">Seller</th>
                        <th className="py-3 px-3 text-left font-semibold text-gray-600">Species</th>
                        <th className="py-3 px-3 text-right font-semibold text-gray-600">Qty (kg)</th>
                        <th className="py-3 px-3 text-right font-semibold text-gray-600">Price/kg</th>
                        <th className="py-3 px-3 text-right font-semibold text-gray-600">Total (TZS)</th>
                        <th className="py-3 px-3 text-center font-semibold text-gray-600">Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      {report.orders.map(o => (
                        <tr key={o.id} className="border-b border-gray-100 hover:bg-gray-50">
                          <td className="py-2.5 px-3 font-bold">#{o.id}</td>
                          <td className="py-2.5 px-3 text-xs">
                            <p>{o.date}</p>
                            <p className="text-gray-500">{o.time}</p>
                          </td>
                          <td className="py-2.5 px-3">
                            <p className="font-medium">{o.buyer_name}</p>
                            <p className="text-xs text-gray-500">{o.buyer_phone}</p>
                          </td>
                          <td className="py-2.5 px-3">
                            <p className="font-medium">{o.seller_name}</p>
                            <p className="text-xs text-gray-500">{o.seller_phone}</p>
                          </td>
                          <td className="py-2.5 px-3">{o.species}</td>
                          <td className="py-2.5 px-3 text-right">{o.quantity_kg}</td>
                          <td className="py-2.5 px-3 text-right">{o.price_tzs.toLocaleString()}</td>
                          <td className="py-2.5 px-3 text-right font-bold">{o.total_value.toLocaleString()}</td>
                          <td className="py-2.5 px-3 text-center">{getStatusBadge(o.status)}</td>
                        </tr>
                      ))}
                    </tbody>
                    {report.orders.length > 0 && stats && (
                      <tfoot className="bg-gray-50 font-bold">
                        <tr>
                          <td className="py-3 px-3" colSpan="5">TOTAL</td>
                          <td className="py-3 px-3 text-right">{stats.totalQty.toFixed(2)}</td>
                          <td className="py-3 px-3"></td>
                          <td className="py-3 px-3 text-right text-cyan-700">TZS {stats.totalValue.toLocaleString()}</td>
                          <td></td>
                        </tr>
                      </tfoot>
                    )}
                  </table>
                  {report.orders.length === 0 && (
                    <p className="text-center text-gray-500 py-8">No transactions found for this filter</p>
                  )}
                </div>
              </div>
            )}

            {/* Footer */}
            <div className="px-8 py-3 bg-gray-50 border-t border-gray-200 text-center">
              <p className="text-xs text-gray-500">© 2026 Samaki Smart AI • State University of Zanzibar • Official Document</p>
            </div>
          </div>
        ) : null}
      </div>
    </>
  )
}